### ISSUE TITLE
Fix WebpackShellPlugin code to work on macOS/Windows

### ISSUE THREAD

**Issue by timwoj** [timwoj/shadowcraft-ui-python#132]
The version of `find` on macOS doesn't support the `printf` argument:

```
Executing pre-build scripts
find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
```

Windows has other issues.

**Comment by timwoj** [comment]
Windows prints this mess:

```
Executing pre-build scripts                                                                                   0% compileFIND: Parameter format not correct
FIND: Parameter format not correct
C:\Users\mcore\Source\Repos\shadowcraft-ui-react\node_modules\webpack-shell-plugin\lib\index.js:168
        throw error;
        ^

Error: Command failed: find shadowcraft_ui/static/css -name "main-*.css" -printf "%Ts   %p
" | sort -nr | cut -f2 | tail -n +5 | xargs rm -f
FIND: Parameter format not correct

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

`FIND` is a built-in command on Windows and doesn't resemble gnu find in any way shape or form.
